 <div class="zest-ov-main"> 
    <div class="zest-row">
     <div class="zest-large-12 zest-columns">
     <div class="zest-row zest-collapse">
            <div class="zest-congrats-user">
                <h1>
                    <a href="<?php echo $block->getfaqurl(); ?>" target="_blank" class="zest-pull-right">FAQ?</a>
                    Greats! You selected ZestMoney instant EMI option.<br>And this is how it works.</h1>
                </div>
            </div>    
            <div class="zest-row zest-collapse">
                <div class="zest-steps-img">
                    <img class="zest-desktop-view" src="<?php echo $block->getViewFileUrl('Zest_ZestMoney::images/01.png'); ?>">
                    <img class="zest-mobile-view" src="<?php echo $block->getViewFileUrl('Zest_ZestMoney::images/mobile-2.png'); ?>">
                </div> 
            </div> 
        </div>
    </div>
</div>
